"""Queue-based graph execution engine."""

from __future__ import annotations

import logging
import queue
from collections.abc import Generator, Sequence
from typing import final

from graphon.engine_events.base import (
    EngineEvent,
)
from graphon.engine_events.graph import (
    GraphRunAbortedEvent,
    GraphRunFailedEvent,
    GraphRunPartialSucceededEvent,
    GraphRunPausedEvent,
    GraphRunStartedEvent,
    GraphRunSucceededEvent,
)
from graphon.entities.workflow_start_reason import WorkflowStartReason
from graphon.graph.graph import Graph
from graphon.runtime.execution import ROOT_FRAME_ID
from graphon.runtime.read_only_wrappers import ReadOnlyRuntimeStateWrapper
from graphon.runtime.runtime_state import RuntimeState

from .command.builtin.in_memory import InMemoryChannel
from .command.entities import AbortCommand
from .command.processor import CommandProcessor
from .command.protocol import CommandChannel
from .container_handler import (
    ContainerHandlerFactory,
    IterationContainerHandler,
    LoopContainerHandler,
)
from .dispatcher import Dispatcher
from .event.processor import NodeEventProcessor
from .event.stream import EventStream
from .frame import FrameRegistry
from .layer import Layer
from .ready_queue import ResumeTask, StartTask
from .worker import DispatchTask, WorkerPool

logger = logging.getLogger(__name__)


_DEFAULT_CONTAINER_HANDLER_FACTORIES: tuple[ContainerHandlerFactory, ...] = (
    LoopContainerHandler,
    IterationContainerHandler,
)


@final
class Engine:
    """Coordinate graph scheduling, worker execution, and event delivery."""

    def __init__(
        self,
        graph: Graph,
        runtime_state: RuntimeState,
        command_channel: CommandChannel | None = None,
        workers: int = 5,
        container_handler_factories: Sequence[ContainerHandlerFactory] = (),
    ) -> None:
        """Build an engine for one graph execution.

        ``workers`` is the fixed number of node-execution threads owned by this
        engine. It must be a positive integer; rejecting invalid values before
        any runtime state is attached avoids creating an engine that can never
        consume ready tasks.

        Args:
            graph: Graph structure executed by this engine.
            runtime_state: Mutable runtime state associated with ``graph``.
            command_channel: External command source for pause, abort, and updates.
                A process-local in-memory channel is created when omitted.
            workers: Fixed number of worker threads to create while running.
            container_handler_factories: Additional container handler factories.

        Raises:
            ValueError: If ``workers`` is not a positive integer.

        """
        if not isinstance(workers, int) or isinstance(workers, bool) or workers < 1:
            msg = "workers must be a positive integer"
            raise ValueError(msg)

        # Bind runtime state to current workflow context
        self._graph = graph
        self._runtime_state = runtime_state
        self._command_channel = (
            command_channel if command_channel is not None else InMemoryChannel()
        )
        self._layers: list[Layer] = []

        # Graph execution tracks the overall execution state
        self._graph_execution = self._runtime_state.graph_execution

        # Queue for state-transition work generated by workers.
        dispatch_queue: queue.Queue[DispatchTask] = queue.Queue()

        # === State Management ===
        self._frame_registry = FrameRegistry()
        root_frame = self._frame_registry.create(
            frame_id=ROOT_FRAME_ID,
            container_id="",
            graph=self._graph,
            state=self._runtime_state,
        )
        self._scheduler = root_frame.scheduler

        # === Event Streaming ===
        self._event_stream = EventStream(self._layers)

        # === Command Processing ===
        # Processes external commands (e.g., abort requests)
        command_processor = CommandProcessor(
            command_channel=self._command_channel,
            graph_execution=self._graph_execution,
            frame_registry=self._frame_registry,
        )

        # === Worker Pool Setup ===
        handlers = (
            factory(self._frame_registry)
            for factory in (
                *_DEFAULT_CONTAINER_HANDLER_FACTORIES,
                *container_handler_factories,
            )
        )
        self._container_handlers = {handler.node_type: handler for handler in handlers}

        # Create worker pool for parallel node execution
        self._worker_pool = WorkerPool(
            ready_queue=self._runtime_state.ready_queue,
            dispatch_queue=dispatch_queue,
            frame_registry=self._frame_registry,
            layers=self._layers,
            execution_context=self._runtime_state.execution_context,
            workers=workers,
        )

        # Applies node events to graph and frame state.
        event_processor = NodeEventProcessor(
            graph_execution=self._graph_execution,
            event_stream=self._event_stream,
            frame_registry=self._frame_registry,
            container_handlers=self._container_handlers,
        )

        # Dispatches events and manages execution flow
        self._dispatcher = Dispatcher(
            dispatch_queue=dispatch_queue,
            event_processor=event_processor,
            graph_execution=self._graph_execution,
            scheduler=self._scheduler,
            command_processor=command_processor,
            worker_pool=self._worker_pool,
            event_stream=self._event_stream,
        )

        # === Validation ===
        # Ensure all nodes share the same RuntimeState instance
        self._validate_runtime_state_consistency()

    def _validate_runtime_state_consistency(self) -> None:
        """Validate that all nodes share the same RuntimeState."""
        expected_state_id = id(self._runtime_state)
        for node in self._graph.nodes.values():
            if id(node.runtime_state) != expected_state_id:
                msg = (
                    "RuntimeState consistency violation: Node "
                    f"'{node.id}' has a different instance"
                )
                raise ValueError(msg)

    def add_layer(self, layer: Layer) -> None:
        """Register and bind one extension layer to this engine.

        The layer receives a read-only view of this engine's runtime state and
        the command channel immediately. Its lifecycle hooks are invoked later
        by :meth:`run`; registration itself does not start graph execution.
        """
        self._layers.append(layer)
        layer.initialize(
            ReadOnlyRuntimeStateWrapper(self._runtime_state),
            self._command_channel,
        )

    def request_abort(self, reason: str | None = None) -> None:
        """Queue an abort command for this engine."""
        self._command_channel.send_command(
            AbortCommand(reason=reason or "User requested abort"),
        )

    def run(self) -> Generator[EngineEvent, None, None]:
        """Execute the graph using the modular architecture.

        Yields:
            `EngineEvent` instances emitted during workflow execution.

        """
        try:
            yield from self._run_graph()
        except Exception as error:
            failed_event = GraphRunFailedEvent(
                error=str(error),
                exceptions_count=self._graph_execution.exceptions_count,
            )
            self._event_stream.notify_layers(failed_event)
            yield failed_event
            raise
        finally:
            self._stop_execution()

    def _run_graph(self) -> Generator[EngineEvent, None, None]:
        self._event_stream.reset()
        self._initialize_layers()
        resume = self._graph_execution.started
        if resume:
            self._graph_execution.paused = False
            self._graph_execution.pause_reasons = []
        else:
            self._graph_execution.start()

        started_event = GraphRunStartedEvent(
            reason=(
                WorkflowStartReason.RESUMPTION
                if resume
                else WorkflowStartReason.INITIAL
            ),
        )
        self._event_stream.notify_layers(started_event)
        yield started_event
        self._start_execution(resume=resume)
        yield from self._event_stream.emit_events()
        yield from self._emit_terminal_events()

    def _emit_terminal_events(self) -> Generator[EngineEvent, None, None]:
        if self._graph_execution.aborted:
            abort_reason = "Workflow execution aborted by user command"
            if self._graph_execution.error:
                abort_reason = str(self._graph_execution.error)
            aborted_event = GraphRunAbortedEvent(
                reason=abort_reason,
                outputs=self._runtime_state.outputs,
            )
            self._event_stream.notify_layers(aborted_event)
            yield aborted_event
            return

        if self._graph_execution.error is not None:
            raise self._graph_execution.error

        if self._graph_execution.paused:
            pause_reasons = self._graph_execution.pause_reasons
            if not pause_reasons:
                msg = "pause_reasons should not be empty when execution is paused."
                raise RuntimeError(msg)
            # Ensure we have a valid PauseReason for the event
            paused_event = GraphRunPausedEvent(
                reasons=pause_reasons,
                outputs=self._runtime_state.outputs,
            )
            self._event_stream.notify_layers(paused_event)
            yield paused_event
            return

        outputs = self._runtime_state.outputs
        exceptions_count = self._graph_execution.exceptions_count
        if exceptions_count > 0:
            partial_event = GraphRunPartialSucceededEvent(
                exceptions_count=exceptions_count,
                outputs=outputs,
            )
            self._event_stream.notify_layers(partial_event)
            yield partial_event
            return

        succeeded_event = GraphRunSucceededEvent(
            outputs=outputs,
        )
        self._event_stream.notify_layers(succeeded_event)
        yield succeeded_event

    def _initialize_layers(self) -> None:
        """Initialize layers with context."""
        for layer in self._layers:
            try:
                layer.on_graph_start()
            except Exception:
                logger.exception(
                    "Layer %s failed on_graph_start",
                    layer.__class__.__name__,
                )

    def _start_execution(self, *, resume: bool) -> None:  # ruff:ignore[complex-structure]
        """Start execution subsystems."""
        ready_tasks = []
        if resume:
            for frame_state in self._runtime_state.container_frames():
                run_state = self._runtime_state.get_container_run(
                    frame_state.parent_invocation_id,
                )
                parent_node = self._frame_registry[run_state.frame_id].graph.nodes[
                    run_state.node_id
                ]
                self._container_handlers[parent_node.node_type].restore_frame(
                    frame_state,
                )
            for run_state in self._runtime_state.container_runs():
                self._frame_registry[run_state.frame_id].scheduler.track_unfinished(
                    run_state.node_id
                )
            queued_tasks = self._runtime_state.ready_queue.take_all()
            deferred_tasks = self._runtime_state.take_deferred_ready_tasks()
            ready_tasks = [*queued_tasks, *deferred_tasks]
            try:
                for task in ready_tasks:
                    if isinstance(task, StartTask):
                        self._frame_registry[task.frame_id].scheduler.track_unfinished(
                            task.node_id,
                        )
                    elif isinstance(task, ResumeTask):
                        self._runtime_state.get_container_run(task.invocation_id)
            except Exception:
                for task in queued_tasks:
                    self._runtime_state.ready_queue.put(task)
                for task in deferred_tasks:
                    self._runtime_state.defer_ready_task(task)
                raise

        # ReadyQueue.put() may block, so consumers must exist before scheduling.
        self._worker_pool.start()

        if resume:
            for task in ready_tasks:
                self._runtime_state.enqueue_ready_task(task)
        else:
            root_node = self._graph.root_node
            self._scheduler.enqueue_node(root_node.id)

        self._dispatcher.start()

    def _stop_execution(self) -> None:
        """Stop execution subsystems."""
        self._dispatcher.stop()
        self._worker_pool.stop()
        # Don't mark complete here as the dispatcher already does it

        # Notify layers
        for layer in self._layers:
            try:
                layer.on_graph_end(self._graph_execution.error)
            except Exception:
                logger.exception(
                    "Layer %s failed on_graph_end",
                    layer.__class__.__name__,
                )

    # Public property accessors for attributes that need external access
    @property
    def graph(self) -> Graph:
        """Get the graph bound to this engine."""
        return self._graph

    @property
    def runtime_state(self) -> RuntimeState:
        """Get the runtime state bound to this engine."""
        return self._runtime_state
